apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hello-World-App
  labels:
    app: Hello-World-App
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Hello-World-App
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Hello-World-App
    spec:
      containers:
        - image: 664117675373.dkr.ecr.us-east-1.amazonaws.com/udacity:latest
          name: Hello-World-App
          ports:
            - containerPort: 80
              name: http-server