apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp
  labels:
    app: helloworldapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworldapp
    spec:
      containers:
        - image: 664117675373.dkr.ecr.us-east-1.amazonaws.com/udacity:latest
          name: udacity
          ports:
            - containerPort: 80
              name: http-server